all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
k8s_cluster:
  children:
    master:
      hosts:
        k8s-master:
          ansible_host: "{{ vault_master_ip }}"
          ansible_user: "{{ vault_ansible_user }}"
          ansible_ssh_private_key_file: "{{ vault_ssh_private_key }}"
    workers:
      hosts:
        k8s-worker1:
          ansible_host: "{{ vault_worker1_ip }}"
          ansible_user: "{{ vault_ansible_user }}"
          ansible_ssh_private_key_file: "{{ vault_ssh_private_key }}"
